# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Pavol Rusnak
tagline:             'hacker'
description:         'Pavol Rusnak'
url:                 http://gk2.sk
baseurl:             http://gk2.sk
paginate:            5

# About/contact
author:
  name:              Pavol Rusnak
  url:               https://twitter.com/pavolrusnak
  email:             stick@gk2.sk
