gems:
  - jekyll-paginate
  - jekyll-sitemap

permalink:           /:title/

title:               Pavol Rusnak
tagline:             '#hacker #crypto #opensource #openhardware #opendata'
description:         'Pavol Rusnak'
url:                 http://gk2.sk
baseurl:             ''
paginate:            5

author:
  name:              Pavol Rusnak
  url:               https://twitter.com/pavolrusnak
  email:             stick@gk2.sk
